# Generated by Django 5.0 on 2023-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_name', models.CharField(max_length=100)),
                ('barber_slogan', models.TextField()),
                ('barber_logo', models.ImageField(upload_to='logo/')),
                ('barber_book_logo', models.ImageField(upload_to='booking_logo/')),
            ],
        ),
    ]
