# Generated by Django 5.0 on 2023-12-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='barbers/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('icon', models.CharField(choices=[('bi-facebook', 'Facebook'), ('bi-instagram', 'Instagram'), ('bi-whatsapp', 'Whatsapp'), ('bi-twitch', 'Twitch'), ('bi-twitter', 'Twitter'), ('bi-telegram', 'Telegram')], max_length=100)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='aboutus_app.barber')),
            ],
        ),
    ]
