# Generated by Django 5.0 on 2023-12-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('branch', models.CharField(max_length=150)),
                ('number_of_people', models.PositiveSmallIntegerField()),
                ('book_date', models.DateField()),
                ('book_time', models.TimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('book_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarberWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('rest_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
