# Generated by Django 5.0 on 2023-12-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barberworkingday',
            old_name='rest_time',
            new_name='end_rest_time',
        ),
        migrations.AddField(
            model_name='barberworkingday',
            name='start_rest_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
