# Generated by Django 5.0 on 2023-12-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_rename_rest_time_barberworkingday_end_rest_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
