# Generated by Django 5.0 on 2023-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0003_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberworkingday',
            name='time_each_service',
            field=models.TimeField(null=True),
        ),
    ]
