# Generated by Django 5.0 on 2023-12-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0004_barberworkingday_time_each_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberworkingday',
            name='time_each_service',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
