# Generated by Django 5.0 on 2023-12-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_remove_pricelist_price_remove_pricelist_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
