# Generated by Django 5.0 on 2023-12-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='image',
            field=models.ImageField(null=True, upload_to='price_list/'),
        ),
    ]
