# Generated by Django 5.0 on 2023-12-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('address_map', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('icon', models.CharField(choices=[('bi-facebook', 'Facebook'), ('bi-instagram', 'Instagram'), ('bi-whatsapp', 'Whatsapp'), ('bi-twitch', 'Twitch'), ('bi-twitter', 'Twitter'), ('bi-telegram', 'Telegram')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('open_at', models.CharField(max_length=10)),
                ('close_at', models.CharField(max_length=10)),
            ],
        ),
    ]
