# Generated by Django 5.0 on 2023-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='address_map',
            field=models.TextField(),
        ),
    ]
