# Generated by Django 5.0 on 2023-12-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0002_alter_contactus_address_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='address_map',
        ),
    ]
